language: csharp
mono: none
dotnet: 2.1.300

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test FhirDeathRecord.Tests/DeathRecord.Tests.csproj
 - dotnet run -p FhirDeathRecord.CLI
 - dotnet run -p FhirDeathRecord.CLI ije FhirDeathRecord.CLI/1.xml
 - dotnet run -p FhirDeathRecord.CLI FhirDeathRecord.CLI/1.xml
