language: csharp
mono: none
dotnet: 2.1

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test VRDR.Tests/DeathRecord.Tests.csproj
 - dotnet run -p VRDR.CLI json2json VRDR.CLI/1.json
 - dotnet run -p VRDR.CLI xml2xml VRDR.CLI/1.xml
 - dotnet run -p VRDR.CLI description VRDR.CLI/1.xml
 - dotnet run -p VRDR.CLI description VRDR.CLI/1.json
 - dotnet run -p VRDR.CLI roundtrip-ije VRDR.CLI/1.xml
 - dotnet run -p VRDR.CLI roundtrip-ije VRDR.CLI/1.json
 - dotnet run -p VRDR.CLI roundtrip-all VRDR.CLI/1.xml
 - dotnet run -p VRDR.CLI roundtrip-all VRDR.CLI/1.json
 - ./VRDR.Tests/test_translation_service.sh
