language: csharp
mono: none
dotnet: 2.1

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test FhirDeathRecord.Tests/DeathRecord.Tests.csproj
 - dotnet run -p FhirDeathRecord.CLI json2json FhirDeathRecord.CLI/1.json
 - dotnet run -p FhirDeathRecord.CLI xml2xml FhirDeathRecord.CLI/1.xml
 - dotnet run -p FhirDeathRecord.CLI description FhirDeathRecord.CLI/1.xml
 - dotnet run -p FhirDeathRecord.CLI description FhirDeathRecord.CLI/1.json
 - dotnet run -p FhirDeathRecord.CLI roundtrip-ije FhirDeathRecord.CLI/1.xml
 - dotnet run -p FhirDeathRecord.CLI roundtrip-ije FhirDeathRecord.CLI/1.json
 - dotnet run -p FhirDeathRecord.CLI roundtrip-all FhirDeathRecord.CLI/1.xml
 - dotnet run -p FhirDeathRecord.CLI roundtrip-all FhirDeathRecord.CLI/1.json
 - ./FhirDeathRecord.Tests/test_translation_service.sh
