name: Run Test Suite on PR or push to master

on:
  push:
    branches:
      - master
      - 'IG-develop-*'
  pull_request:
    branches:
      - master
      - 'IG-develop-*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.815
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.408
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: .net Side by Side
      run: |
        rsync -a ${DOTNET_ROOT/3.1.408/2.1.815}/* $DOTNET_ROOT/
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
          echo "* dotnet test VRDR.Tests/DeathRecord.Tests.csproj"
          dotnet test VRDR.Tests/DeathRecord.Tests.csproj
          echo "* dotnet run --project VRDR.CLI json2json VRDR.CLI/1_wJurisdiction.json"
          dotnet run --project VRDR.CLI json2json VRDR.CLI/1_wJurisdiction.json
          echo "* dotnet run --project VRDR.CLI xml2xml VRDR.CLI/1_wJurisdiction.xml"
          dotnet run --project VRDR.CLI xml2xml VRDR.CLI/1_wJurisdiction.xml
          echo "* dotnet run --project VRDR.CLI description VRDR.CLI/1_wJurisdiction.xml"
          dotnet run --project VRDR.CLI description VRDR.CLI/1_wJurisdiction.xml
          echo "* dotnet run --project VRDR.CLI description VRDR.CLI/1_wJurisdiction.json"
          dotnet run --project VRDR.CLI description VRDR.CLI/1_wJurisdiction.json
          echo "* ! dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1.xml"
          ! dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1.xml
          echo "* ! dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1.json"
          ! dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1.json
          echo "* dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1_wJurisdiction.xml"
          dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1_wJurisdiction.xml
          echo "* dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1_wJurisdiction.json"
          dotnet run --project VRDR.CLI roundtrip-ije VRDR.CLI/1_wJurisdiction.json
          echo "* dotnet run --project VRDR.CLI roundtrip-all VRDR.CLI/1_wJurisdiction.xml"
          dotnet run --project VRDR.CLI roundtrip-all VRDR.CLI/1_wJurisdiction.xml
          echo "* dotnet run --project VRDR.CLI roundtrip-all VRDR.CLI/1_wJurisdiction.json"
          dotnet run --project VRDR.CLI roundtrip-all VRDR.CLI/1_wJurisdiction.json
          echo "* ./VRDR.Tests/test_translation_service.sh"
          echo " ./VRDR.Tests/test_translation_service.sh DISABLE FOR 1.3"
